### PR TITLE
Allow post types to define support

### PR DESCRIPTION
**Pull request by srtfisher**
Adds a new post type support `clone-replace` that will define if a post type has support for Clone and Replace. By default, all public post types are supported.

## For the reviewer, please review the commit that has the changed work in this PR only since #19 has the rest: [`4be9078` (#20)](https://github.com/alleyinteractive/clone-replace/pull/20/commits/4be9078148f0e750645fe3ac6cd3b7724adc9b2d)

Depends on https://github.com/alleyinteractive/clone-replace/pull/19

### CODE REVIEW

**Review by mslinnea — APPROVED** [review]
🐴

**Comment by montchr** [comment]
Since #19's approach to adding Gutenberg support was superseded by the approach merged to `main` in #21  (and iterated upon in #26 and #28), this feature will need to be added without the changes from #19.

**Review by montchr — CHANGES_REQUESTED** [review]
See previous comment.

**Comment by montchr** [comment]
Superseded by #30

**Pull request closed without merging**
